INSERT INTO ACCOUNT VALUES (nextval('ACCOUNT_SEQUENCE'), 'admin', 'password');
INSERT INTO ACCOUNT VALUES(nextval('ACCOUNT_SEQUENCE'), 'user', 'password');

INSERT INTO ROLE VALUES(nextval('ROLE_SEQUENCE'), 'ADMIN');
INSERT INTO ROLE VALUES(nextval('ROLE_SEQUENCE'), 'USER');

INSERT INTO ACCOUNT_ROLE_MAPPING VALUES (
  (SELECT ID FROM ACCOUNT WHERE LOWER (USERNAME) = 'admin'),
  (SELECT ID FROM ROLE WHERE ROLE_NAME = 'ADMIN')
);
INSERT INTO ACCOUNT_ROLE_MAPPING VALUES (
  (SELECT ID FROM ACCOUNT WHERE LOWER (USERNAME) = 'user'),
  (SELECT ID FROM ROLE WHERE ROLE_NAME = 'USER')
);

INSERT INTO FUNCTION VALUES (nextval('FUNCTION_SEQUENCE'), 'Hello', 'Main page', null);
INSERT INTO FUNCTION VALUES (nextval('FUNCTION_SEQUENCE'), 'Admins', 'Disclosure for admins', (SELECT ID FROM FUNCTION WHERE FUNCTION_NAME = 'Hello'));
INSERT INTO FUNCTION VALUES (nextval('FUNCTION_SEQUENCE'), 'Users', 'Disclosure for users', (SELECT ID FROM FUNCTION WHERE FUNCTION_NAME = 'Hello'));
INSERT INTO FUNCTION VALUES (nextval('FUNCTION_SEQUENCE'), 'User', 'User management', null);
INSERT INTO FUNCTION VALUES (nextval('FUNCTION_SEQUENCE'), 'Role', 'Role management', null);

--  ADMIN acl
INSERT INTO ROLE_FUNCTION_MAPPING VALUES (
  (SELECT ID FROM ROLE WHERE ROLE_NAME = 'ADMIN'),
  (SELECT ID FROM FUNCTION WHERE FUNCTION_NAME = 'Hello')
);
INSERT INTO ROLE_FUNCTION_MAPPING VALUES (
  (SELECT ID FROM ROLE WHERE ROLE_NAME = 'ADMIN'),
  (SELECT ID FROM FUNCTION WHERE FUNCTION_NAME = 'Admins')
);
INSERT INTO ROLE_FUNCTION_MAPPING VALUES (
  (SELECT ID FROM ROLE WHERE ROLE_NAME = 'ADMIN'),
  (SELECT ID FROM FUNCTION WHERE FUNCTION_NAME = 'User')
);
INSERT INTO ROLE_FUNCTION_MAPPING VALUES (
  (SELECT ID FROM ROLE WHERE ROLE_NAME = 'ADMIN'),
  (SELECT ID FROM FUNCTION WHERE FUNCTION_NAME = 'Role')
);

-- USER acl
INSERT INTO ROLE_FUNCTION_MAPPING VALUES (
  (SELECT ID FROM ROLE WHERE ROLE_NAME = 'USER'),
  (SELECT ID FROM FUNCTION WHERE FUNCTION_NAME = 'Hello')
);
INSERT INTO ROLE_FUNCTION_MAPPING VALUES (
  (SELECT ID FROM ROLE WHERE ROLE_NAME = 'USER'),
  (SELECT ID FROM FUNCTION WHERE FUNCTION_NAME = 'Users')
);