DROP TABLE IF EXISTS ACCOUNT_ROLE_MAPPING;
DROP TABLE IF EXISTS ROLE_FUNCTION_MAPPING;
DROP TABLE IF EXISTS ACCOUNT;
DROP TABLE IF EXISTS ROLE;
DROP TABLE IF EXISTS FUNCTION;
DROP SEQUENCE IF EXISTS ACCOUNT_SEQUENCE;
DROP SEQUENCE IF EXISTS ROLE_SEQUENCE;
DROP SEQUENCE IF EXISTS FUNCTION_SEQUENCE;

CREATE TABLE ACCOUNT (
  ID SERIAL PRIMARY KEY,
  USERNAME VARCHAR(60) NOT NULL,
  CREDENTIALS VARCHAR(20) NOT NULL
);

CREATE TABLE ROLE (
  ID SERIAL PRIMARY KEY,
  ROLE_NAME VARCHAR(60) NOT NULL
);

CREATE TABLE FUNCTION (
  ID SERIAL PRIMARY KEY,
  FUNCTION_NAME VARCHAR(20) NOT NULL,
  DESCRIPTION VARCHAR(100),
  PARENT_ID INTEGER REFERENCES FUNCTION(ID)
);

CREATE TABLE ACCOUNT_ROLE_MAPPING (
  ACCOUNT_ID INTEGER REFERENCES ACCOUNT(ID),
  ROLE_ID INTEGER REFERENCES ROLE(ID)
);

CREATE TABLE ROLE_FUNCTION_MAPPING (
  ROLE_ID INTEGER REFERENCES ROLE(ID),
  FUNCTION_ID INTEGER REFERENCES FUNCTION(ID)
);

CREATE SEQUENCE ACCOUNT_SEQUENCE
  START 1
  INCREMENT 1;

CREATE SEQUENCE FUNCTION_SEQUENCE
  START 1
  INCREMENT 1;

CREATE SEQUENCE ROLE_SEQUENCE
  START 1
  INCREMENT 1;